name: Release Wasmo Docker Images
inputs:
    version:
        description: "Version number"

runs:
  using: composite
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Update server package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: server/package.json
          field: version
          value: ${{ inputs.version }}

      - name: Update ui package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: ui/package.json
          field: version
          value: ${{ inputs.version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: MAIF/wasmo
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: maif/wasmo:${{ inputs.version }},maif/wasmo:latest
