[package]
name = "your-package-name"
version = "1.0.0"
description = "Package description for your package"

# Comment this line if you don't want to add a README to your package
readme = "./README.md"

# the source must be a value included in the configuration file
[[module]]
name = "your-package-name"
source = "package-version.wasm"