name: Build Wasmo & CLI binaries

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"

jobs:
    all:
        runs-on: ubuntu-latest
        name: Build Wasmo & CLI binaries
        steps:
            - uses: actions/checkout@v4
            
            - name: Release Wasmo Docker Images
              uses: ./actions/action-docker
              with:
                version: ${{ inputs.version }}

            - name: Build Wasmo CLI binaries
              uses: ./actions/action-cli
              with:
                version: ${{ inputs.version }}

            - name: Push on crates.io
              uses: ./actions/action-cratesio
    
        
