name: Build Wasmo & CLI binaries

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"

jobs:
    all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Release Wasmo Docker Images
              uses: ./workflows/docker
              with:
                version: ${{ inputs.version }}
            - name: Build Wasmo CLI binaries
              uses: ./workflows/cli
              with:
                version: ${{ inputs.version }}
            - name: Push on crates.io
              uses: ./workflows/cratesio
    
        
